services:
  data:
    image: busybox:latest
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/app
    entrypoint: tail -f /dev/null

  app:
    build: docker/php-with-xdebug
    working_dir: /app
    volumes_from:
      - data
    depends_on:
      - db


  db:
    image: mysql:8.0.0
    restart: always
    volumes:
      - ./data_mysql:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 5307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shared
      MYSQL_USER: root
      MYSQL_PASSWORD: root
